version: '3.7'

services:
  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  alertmanager:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
      - "traefik.http.middlewares.prom-basic-auth.basicauth.users=${ADMIN_USER}:${HASHED_PASSWORD}"
      - "traefik.http.routers.alertmanager.entrypoints=websecure"
      - "traefik.http.routers.alertmanager.tls.certresolver=cloudflare"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.${DOMAIN}`)"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
      - "traefik.http.routers.alertmanager.middlewares=prom-basic-auth"

  unsee:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
      - "traefik.http.middlewares.prom-basic-auth.basicauth.users=${ADMIN_USER}:${HASHED_PASSWORD}"
      - "traefik.http.routers.unsee.entrypoints=websecure"
      - "traefik.http.routers.unsee.tls.certresolver=cloudflare"
      - "traefik.http.routers.unsee.rule=Host(`unsee.${DOMAIN}`)"
      - "traefik.http.services.unsee.loadbalancer.server.port=8080"
      - "traefik.http.routers.unsee.middlewares=prom-basic-auth"

  prometheus:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
      - "traefik.http.middlewares.prom-basic-auth.basicauth.users=${ADMIN_USER}:${HASHED_PASSWORD}"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=cloudflare"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${DOMAIN}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=prom-basic-auth"
